# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy_extensions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: npm run build
      -  uses: joehan/action-extensions-deploy@v0-alpha5
         with:
            # Firebase service account JSON
            firebaseServiceAccount:  "${{ secrets.FIREBASE_DEPLOY_KEY }}"
            # The location of your firebase.json file, relative to the root of your directory
            entryPoint: .
            project: joehanley-public
